sign-commit = true
sign-tag = true
# Get rid of the default cargo-release "chore: " prefix in messages as we don't
# use semantic commits in this repository.
pre-release-commit-message = "Release {{crate_name}} version {{version}}"
tag-message = "Release {{crate_name}} version {{version}}"
